# Generated by Django 4.1 on 2022-08-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpostsapp', '0002_message_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Имя пользователя'),
        ),
    ]
